### ISSUE TITLE
assets branch

### ISSUE THREAD

**Issue by szepeviktor** [xwp/wp-dev-lib#86]
May I suggest assets to be in a separate **git** branch?

**Comment by westonruter** [comment]
You're talking about for `svn-push`, right? I can see how this would be useful.

**Comment by szepeviktor** [comment]
I think access to assets are rearly needed.

**Comment by szepeviktor** [comment]
> I can see how this would be useful.

Have you meant `can't`?

**Comment by westonruter** [comment]
No. I *can* see that it could be useful to obtain the `assets` directory for WordPress.org from another branch instead of an `assets` directory. However, it is very useful to be in the same branch and they can be accessed from the README. See for example: https://github.com/xwp/wp-widget-customizer#screenshots

**Comment by szepeviktor** [comment]
I see.
Is it possible to link images from another branch?

**Comment by westonruter** [comment]
I don't think you can do it as cleanly on GitHub.

**Comment by szepeviktor** [comment]
```
![The Loop](https://github.com/szepeviktor/frontend-debugger/raw/assets/screenshot-1.jpg)
<hr/>
![The Header](https://github.com/szepeviktor/frontend-debugger/raw/assets/screenshot-2.jpg)
<hr/>
![Included files](https://github.com/szepeviktor/frontend-debugger/raw/assets/screenshot-3.jpg)
```
https://github.com/szepeviktor/frontend-debugger

What is the culprit?

**Comment by valendesigns** [comment]
Raw files aren't cached and could put a lot of stress on Github.
